### PR TITLE
Style fixes, Singletons, Exceptions instead of Checks

### PR DESCRIPTION
**Pull request by ComiR**
Effectively an updated version of #4.

### CODE REVIEW

**Comment by ComiR** [comment]
With https://github.com/neos/metadata/pull/6 merged, this should pass the tests again. Can you ping travis @daniellienert?

**Comment by ComiR** [comment]
Just realized we require `^2.0`. Perhaps releasing neos/metadata 2.0.1 and requiring `^2.0.1` is the way to go?

**Comment by daniellienert** [comment]
Jep, that's the problem. Another way would be to alias dev-master as 2.0 for the tests. This would avoid releasing on every API change.

**Comment by daniellienert** [comment]
@ComiR: unfortunately the build also fails with updated metadata package.

**Comment by ComiR** [comment]
That would be the "standard vs. reality" issue again. Times should always have a timezone, but in reality (i.e. the test case) it doesn't.

**Pull request merged**
